var annotated_dup =
[
    [ "GoNatureAR", "namespace_go_nature_a_r.html", [
      [ "Requests", "namespace_go_nature_a_r_1_1_requests.html", [
        [ "IRequest", "interface_go_nature_a_r_1_1_requests_1_1_i_request.html", "interface_go_nature_a_r_1_1_requests_1_1_i_request" ],
        [ "IResponse", "interface_go_nature_a_r_1_1_requests_1_1_i_response.html", "interface_go_nature_a_r_1_1_requests_1_1_i_response" ],
        [ "OAuth2Request", "class_go_nature_a_r_1_1_requests_1_1_o_auth2_request.html", "class_go_nature_a_r_1_1_requests_1_1_o_auth2_request" ],
        [ "PilotDataRequest", "class_go_nature_a_r_1_1_requests_1_1_pilot_data_request.html", "class_go_nature_a_r_1_1_requests_1_1_pilot_data_request" ],
        [ "PilotDataRequestManager", "class_go_nature_a_r_1_1_requests_1_1_pilot_data_request_manager.html", "class_go_nature_a_r_1_1_requests_1_1_pilot_data_request_manager" ],
        [ "Request", "class_go_nature_a_r_1_1_requests_1_1_request.html", "class_go_nature_a_r_1_1_requests_1_1_request" ],
        [ "Response", "class_go_nature_a_r_1_1_requests_1_1_response.html", "class_go_nature_a_r_1_1_requests_1_1_response" ]
      ] ],
      [ "Sensors", "namespace_go_nature_a_r_1_1_sensors.html", [
        [ "AirQuality", "class_go_nature_a_r_1_1_sensors_1_1_air_quality.html", "class_go_nature_a_r_1_1_sensors_1_1_air_quality" ],
        [ "AirQualityCalculator", "class_go_nature_a_r_1_1_sensors_1_1_air_quality_calculator.html", "class_go_nature_a_r_1_1_sensors_1_1_air_quality_calculator" ],
        [ "CastelfrancoSensors", "class_go_nature_a_r_1_1_sensors_1_1_castelfranco_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_castelfranco_sensors" ],
        [ "CastelfrancoVenetoSensorData", "class_go_nature_a_r_1_1_sensors_1_1_castelfranco_veneto_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_castelfranco_veneto_sensor_data" ],
        [ "ChaniaSensorData", "class_go_nature_a_r_1_1_sensors_1_1_chania_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_chania_sensor_data" ],
        [ "ChaniaSensors", "class_go_nature_a_r_1_1_sensors_1_1_chania_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_chania_sensors" ],
        [ "DundalkSensorData", "class_go_nature_a_r_1_1_sensors_1_1_dundalk_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_dundalk_sensor_data" ],
        [ "DundalkSensors", "class_go_nature_a_r_1_1_sensors_1_1_dundalk_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_dundalk_sensors" ],
        [ "GziraSensorData", "class_go_nature_a_r_1_1_sensors_1_1_gzira_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_gzira_sensor_data" ],
        [ "GziraSensors", "class_go_nature_a_r_1_1_sensors_1_1_gzira_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_gzira_sensors" ],
        [ "ISensor", "interface_go_nature_a_r_1_1_sensors_1_1_i_sensor.html", "interface_go_nature_a_r_1_1_sensors_1_1_i_sensor" ],
        [ "ISensorData", "interface_go_nature_a_r_1_1_sensors_1_1_i_sensor_data.html", "interface_go_nature_a_r_1_1_sensors_1_1_i_sensor_data" ],
        [ "LeuvenSensorData", "class_go_nature_a_r_1_1_sensors_1_1_leuven_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_leuven_sensor_data" ],
        [ "LeuvenSensors", "class_go_nature_a_r_1_1_sensors_1_1_leuven_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_leuven_sensors" ],
        [ "Noise", "class_go_nature_a_r_1_1_sensors_1_1_noise.html", "class_go_nature_a_r_1_1_sensors_1_1_noise" ],
        [ "NovoMestoSensorData", "class_go_nature_a_r_1_1_sensors_1_1_novo_mesto_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_novo_mesto_sensor_data" ],
        [ "NovoMestoSensors", "class_go_nature_a_r_1_1_sensors_1_1_novo_mesto_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_novo_mesto_sensors" ],
        [ "SkellefteaSensorData", "class_go_nature_a_r_1_1_sensors_1_1_skelleftea_sensor_data.html", "class_go_nature_a_r_1_1_sensors_1_1_skelleftea_sensor_data" ],
        [ "SkellefteaSensors", "class_go_nature_a_r_1_1_sensors_1_1_skelleftea_sensors.html", "class_go_nature_a_r_1_1_sensors_1_1_skelleftea_sensors" ],
        [ "ThermalComfort", "class_go_nature_a_r_1_1_sensors_1_1_thermal_comfort.html", "class_go_nature_a_r_1_1_sensors_1_1_thermal_comfort" ],
        [ "ThermalComfortCalculator", "class_go_nature_a_r_1_1_sensors_1_1_thermal_comfort_calculator.html", "class_go_nature_a_r_1_1_sensors_1_1_thermal_comfort_calculator" ]
      ] ],
      [ "AirQualityEffectBehaviour", "class_go_nature_a_r_1_1_air_quality_effect_behaviour.html", null ],
      [ "AirQualityManager", "class_go_nature_a_r_1_1_air_quality_manager.html", "class_go_nature_a_r_1_1_air_quality_manager" ],
      [ "CompanionBehaviour", "class_go_nature_a_r_1_1_companion_behaviour.html", "class_go_nature_a_r_1_1_companion_behaviour" ],
      [ "Credits", "class_go_nature_a_r_1_1_credits.html", "class_go_nature_a_r_1_1_credits" ],
      [ "DataManager", "class_go_nature_a_r_1_1_data_manager.html", "class_go_nature_a_r_1_1_data_manager" ],
      [ "DialogueKey", "struct_go_nature_a_r_1_1_dialogue_key.html", "struct_go_nature_a_r_1_1_dialogue_key" ],
      [ "DialogueScriptableObject", "class_go_nature_a_r_1_1_dialogue_scriptable_object.html", "class_go_nature_a_r_1_1_dialogue_scriptable_object" ],
      [ "DialogueViewHandler", "class_go_nature_a_r_1_1_dialogue_view_handler.html", "class_go_nature_a_r_1_1_dialogue_view_handler" ],
      [ "EnumKey", "class_go_nature_a_r_1_1_enum_key.html", "class_go_nature_a_r_1_1_enum_key" ],
      [ "GameManager", "class_go_nature_a_r_1_1_game_manager.html", "class_go_nature_a_r_1_1_game_manager" ],
      [ "MenuBehaviour", "class_go_nature_a_r_1_1_menu_behaviour.html", null ],
      [ "MusicManager", "class_go_nature_a_r_1_1_music_manager.html", "class_go_nature_a_r_1_1_music_manager" ],
      [ "NarrationManager", "class_go_nature_a_r_1_1_narration_manager.html", "class_go_nature_a_r_1_1_narration_manager" ],
      [ "NarrationScriptableObject", "class_go_nature_a_r_1_1_narration_scriptable_object.html", "class_go_nature_a_r_1_1_narration_scriptable_object" ],
      [ "NoiseColors", "class_go_nature_a_r_1_1_noise_colors.html", "class_go_nature_a_r_1_1_noise_colors" ],
      [ "NoiseEffectBehaviour", "class_go_nature_a_r_1_1_noise_effect_behaviour.html", null ],
      [ "NoiseExposureManager", "class_go_nature_a_r_1_1_noise_exposure_manager.html", "class_go_nature_a_r_1_1_noise_exposure_manager" ],
      [ "OutroManager", "class_go_nature_a_r_1_1_outro_manager.html", "class_go_nature_a_r_1_1_outro_manager" ],
      [ "PanelSpawnOnCamera", "class_go_nature_a_r_1_1_panel_spawn_on_camera.html", null ],
      [ "PilotCanvasViewHandler", "class_go_nature_a_r_1_1_pilot_canvas_view_handler.html", null ],
      [ "RadialViewBehaviour", "class_go_nature_a_r_1_1_radial_view_behaviour.html", null ],
      [ "SpeechProfile", "class_go_nature_a_r_1_1_speech_profile.html", "class_go_nature_a_r_1_1_speech_profile" ],
      [ "ThermalColors", "class_go_nature_a_r_1_1_thermal_colors.html", "class_go_nature_a_r_1_1_thermal_colors" ],
      [ "ThermalComfortManager", "class_go_nature_a_r_1_1_thermal_comfort_manager.html", "class_go_nature_a_r_1_1_thermal_comfort_manager" ],
      [ "ThermalEffectBehaviour", "class_go_nature_a_r_1_1_thermal_effect_behaviour.html", null ]
    ] ],
    [ "EnvFileManager", "class_env_file_manager.html", "class_env_file_manager" ]
];